# Generated by Django 6.0.7 on 2026-08-27 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="temperature_db",
            fields=[
                ("myid", models.AutoField(primary_key=True, serialize=False)),
                ("sensor_id", models.IntegerField()),
                ("temperature", models.FloatField()),
                ("humidity", models.FloatField()),
                ("timestamp", models.DateTimeField(max_length=6)),
            ],
        ),
    ]
