# Generated by Django 5.0.14 on 2026-09-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="userprofile",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=100)),
                ("userSex", models.CharField(max_length=10)),
                ("userschool", models.CharField(max_length=20)),
                ("userinterest", models.TextField()),
                ("userthought", models.TextField()),
            ],
        ),
    ]
